# Generated by Django 5.0 on 2023-12-20 11:06

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("house_number", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="NetworkElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "debt_to_supplier",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Factory"),
                            (1, "Distributor"),
                            (2, "Dealer Center"),
                            (3, "Large Retail Network"),
                            (4, "Individual Entrepreneur"),
                        ]
                    ),
                ),
                (
                    "contacts",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="online_trading_platform.contact",
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        to="online_trading_platform.employee"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"level__lt": 4},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="online_trading_platform.networkelement",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        to="online_trading_platform.product"
                    ),
                ),
            ],
        ),
    ]
