# Generated by Django 5.0 on 2023-12-23 14:08

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField()),
                ("city", models.CharField()),
                ("street", models.CharField()),
                ("house_number", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("model", models.CharField()),
                ("release_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "debt_to_supplier",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Factory"),
                            (1, "Distributor"),
                            (2, "Dealer Center"),
                            (3, "Large Retail Network"),
                            (4, "Individual Entrepreneur"),
                        ]
                    ),
                ),
                (
                    "contacts",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="online_trading_platform.contact",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type__lt": 4},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="online_trading_platform.merchant",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        to="online_trading_platform.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("position", models.CharField()),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="online_trading_platform.merchant",
                    ),
                ),
            ],
        ),
    ]
