# Generated by Django 5.0 on 2023-12-20 12:58

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("online_trading_platform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "debt_to_supplier",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Factory"),
                            (1, "Distributor"),
                            (2, "Dealer Center"),
                            (3, "Large Retail Network"),
                            (4, "Individual Entrepreneur"),
                        ]
                    ),
                ),
                (
                    "contacts",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="online_trading_platform.contact",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type__lt": 4},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="online_trading_platform.merchant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="online_trading_platform.merchant",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="online_trading_platform.merchant",
            ),
        ),
        migrations.DeleteModel(
            name="NetworkElement",
        ),
    ]
