# Generated by Django 5.0 on 2023-12-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "online_trading_platform",
            "0002_merchant_employee_merchant_product_merchant_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="merchant",
        ),
        migrations.AddField(
            model_name="merchant",
            name="products",
            field=models.ManyToManyField(to="online_trading_platform.product"),
        ),
    ]
