# Generated by Django 5.0 on 2023-12-22 16:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "online_trading_platform",
            "0003_remove_product_merchant_merchant_products",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="online_trading_platform.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="contacts",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="online_trading_platform.contact",
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type__lt": 4},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="online_trading_platform.merchant",
            ),
        ),
    ]
